Fix #1040 with uninstalling only installed files.
bleachbit/bleachbit pull request #1146
Opened 2021-04-11 13:25 UTC by rados

Two nsis include files are generated every time by the setup python file but I added them to the repository as well for just in case. In NsisInclude folder - FilesToInstall.nsh & FilesToUninstall.nsh.

2021-04-11 15:17 UTC, abitrolly commented
I read NSIS scripts last time too long ago, but I like the direction this PR is moving. )

2021-04-18 23:31 UTC, az0 requested changes
Rados,

Thank you so much for working on this. I appreciate your continued help. This was my first pass, but I wanted to start giving you some feedback. Please see my review comments.

2021-04-18 23:31 UTC, az0 commented on windows/bleachbit.nsi
> +    Delete $INSTDIR\share\fonts\tahoma.ttf
Let's also delete `$INSTDIR\bleachbit.exe.log` which is generated by py2exe in case of crash

2021-04-18 23:31 UTC, az0 commented on windows/NsisInclude/FilesToInstall.nsh
> +SetOutPath "$INSTDIR\share\locale\af"
The `locale` folder should not be installed for the English-only version of the installer.

2021-04-18 23:31 UTC, az0 commented on windows/bleachbit.nsi
> +    Delete "$INSTDIR\uninstall.exe"
How about removing `uninstall.exe` after SHRED_REGEX_KEY? In case something goes wrong, this could allow a chance to try again.

2021-04-18 23:31 UTC, az0 commented on windows/NsisInclude/FilesToUninstall.nsh
> +Delete "$INSTDIR\libffi-6.dll"
I tested AppVeyor build 1865. The installation seemed OK. When I ran it, it seemed OK, but when I uninstalled it, there were a few files left

libffi-6.dll
libgio-2.0-0.dll
libglib-2.0-0.dll
libgmodule-2.0-0.dll
libgobject-2.0-0.dll
libintl-8.dll
libwinpthread-1.dll
libzzz.dll
msvcr100.dll

These are listed in the uninstall script. I wonder whether the files were locked, but I don't remember seeing that before. I plan to re-test this, so this note can help remind me. 

For now, what do you think about adding `/REBOOTOK` flag to the Delete commands for executables/libraries (pyd, dll, exe)?

2021-04-18 23:31 UTC, az0 commented on windows/NsisInclude/UnInstallLog.nsh
> +    !macro CreateShortCut FilePath FilePointer Pamameters Icon IconIndex
Should Pamameters be Parameters ?

2021-04-18 23:31 UTC, az0 commented on windows/NsisInclude/UnInstallLog.nsh
> +;AddItem macro
I didn't see this file included. Is it needed?

```
$ grep -iR UnInstallLog .
Binary file ./.git/index matches
```

2021-04-30 22:14 UTC, rados commented
I recreated the branch as I needed to fix the Windows related bug which fixes the Linux build. Will create new PR with the same branch name.

2021-04-30 22:27 UTC, az0 commented
I see some good progress here. Thank you, rados. I am not sure whether the new Travis CI notifies you, but there were some build errors: https://travis-ci.com/github/bleachbit/bleachbit/jobs/502382209#L1103

2021-05-01 05:56 UTC, rados commented
> I see some good progress here. Thank you, rados. I am not sure whether the new Travis CI notifies you, but there were some build errors: https://travis-ci.com/github/bleachbit/bleachbit/jobs/502382209#L1103

Yes, I receive all the notifications, thanks. Some tests are failing and part of the reason could be fixed with more sorting of lists (already discussed). I'll check thoroughly in a few days as it is Ester here now. :-)

2021-05-08 19:50 UTC, az0 commented on windows/NsisInclude/FilesToUninstall.nsh
> +Delete "$INSTDIR\libffi-6.dll"
Uninstall is clean in build 1883 (commit) e6af6c433915b38383fda29cde4e8e70eb3e6c68

2021-05-08 19:51 UTC, merged